# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1VEKOb5Vg4nipn1eSQN5rI9QkqfxN8e
"""

we are performing unsupervised clustering on the Diabetes 130-US Hospitals dataset to discover patterns among patients. First, we load the dataset and remove ID columns like encounter ID and patient number, because these are just identifiers and don’t provide meaningful information for clustering. We also drop the readmitted column since clustering doesn’t require a target variable.
Next, we preprocess the data. We separate numeric and categorical features. For numeric features, missing values are filled with the median, and values are scaled so all features are on the same range. For categorical features, missing values are filled with the most frequent category and then converted into numeric columns using one-hot encoding. We combine these preprocessing steps into a ColumnTransformer so that numeric and categorical columns are processed correctly and consistently.
Once preprocessing is done, we apply dimensionality reduction using PCA to reduce the dataset to two components. This helps us visualize the clusters in 2D while keeping most of the variance in the data.
We then apply 2 different clustering algorithms.
1️⃣ KMeans:
KMeans splits the data into a set number of groups. It finds a “center” for each group, then assigns each patient to the group whose center is closest. Think of it like putting similar patients in the same bucket based on their features. It’s fast and works well if groups are fairly even.
2️⃣ DBSCAN:
DBSCAN groups patients based on how close they are to each other. Dense areas form clusters, and points that are far away are considered outliers. It’s good for finding irregular-shaped groups and spotting unusual patients who don’t fit any pattern.

Finally, we visualize the clusters on the 2D PCA projection. Each algorithm assigns cluster labels to each patient, and we plot them with different colors to see how the patients are grouped. This helps identify patterns such as groups of patients with similar characteristics, which could later be used for targeted interventions or analysis.